server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myshop?serverTimezone=GMT%2b8
    username: root
    password: li863561912
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#classpath表示resource文件夹
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件，xml文件是写sql的
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: E:/code/files/

avatarimg:
  upload:
    path: E:/code/files/avatarimg/

productimg:
  upload:
    path: E:/code/files/productimg/

lunboimg:
  upload:
    path: E:/code/files/lunboimg/

